name: pos_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^17.0.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  image: ^4.7.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/saripos_icon_1024.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#005F5C"
  image: assets/branding/saripos_splash_mark_1024.png
  android_12:
    color: "#005F5C"
    image: assets/branding/saripos_splash_mark_1024.png

flutter:
  uses-material-design: true
